# Generated by Django 5.2.4 on 2025-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('ram_type', models.CharField(max_length=256)),
                ('storage', models.IntegerField()),
                ('storage_type', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='laptops/')),
            ],
        ),
    ]
