# Generated by Django 5.2.4 on 2025-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='processor',
        ),
        migrations.AddField(
            model_name='laptop',
            name='core',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='generation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
